services:
  ingestor:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      - SPRING_REDIS_HOST=${SPRING_REDIS_HOST}
      - SPRING_REDIS_PORT=${SPRING_REDIS_PORT}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - KAFKA_TOPIC_EVENTS_STANDARDIZED=${KAFKA_TOPIC_EVENTS_STANDARDIZED}
      - SERVER_PORT=${SERVER_PORT}
    networks:
      - platform_default

networks:
  platform_default:
    external: true