spring:
  application:
    name: correlator

  datasource:
    url: jdbc:postgresql://platform-postgres-1:5432/ciudades
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: platform-kafka-1:9092
    consumer:
      group-id: correlator-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    listener:
      missing-topics-fatal: false

  data:
    redis:
      host: platform-redis-1
      port: 6379

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
    com.ciudadesinteligentes.correlator: DEBUG
